---
exclude: ['README.markdown', 'Makefile', 'component.json']
pygments: true
safe: false

title: {en: "ShanghaiOS", cn: "上海开源聚会"}
switch: {en: "<a href='http://wiredcraft.com/shanghaios/'>中文</a>", cn: "<a href='http://wiredcraft.com/shanghaios/en.html'>en</a>"}
name: {en: "Shanghai <span>Open Source</span> Meetup", cn: "上海<span>开源</span>聚会"}
description: {en: "Meet the Open Source community", cn: "开源爱好者的专业交流平台" }
details: {
	en: { day: "Jun 29, 2013", time: "from 2:00 PM", addr: "666 Fuzhou road, Shanghai" },
	cn: { day: "2013年6月29日", time: "下午2点开始", addr: "上海市 福州路666号 金陵海欣大厦" }
}

url: http://wiredcraft.com/shanghaios/
# ga: 'UA-XXXXXXX-X'